name: CI
on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev dieharder

      - name: Prepare dummy re4_stream (deterministic zeros)
        run: |
          set -euo pipefail
          mkdir -p tools
          printf '#!/usr/bin/env bash\nexec cat /dev/zero\n' > tools/re4_stream_dummy
          chmod +x tools/re4_stream_dummy
          echo "$PWD/tools" >> "$GITHUB_PATH"

      - name: Build CLI
        run: |
          set -euo pipefail
          make -B r4cs_cat

      - name: Smoke: 64 bytes hex format
        env:
          R4_PATH: ${{ github.workspace }}/tools/re4_stream_dummy
          R4_SEED: "1"
        run: |
          set -euo pipefail
          ./r4cs_cat -n 64 -hex | tee out.hex
          grep -Eq '^[0-9a-f]{128}$' out.hex

      - name: Smoke: determinism with R4_SEED
        env:
          R4_PATH: ${{ github.workspace }}/tools/re4_stream_dummy
          R4_SEED: "1"
        run: |
          set -euo pipefail
          ./r4cs_cat -n 4096 > a.bin
          ./r4cs_cat -n 4096 > b.bin
          cmp -s a.bin b.bin

      - name: Upload rng logs (artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: rng_reports_${{ github.sha }}
          path: |
            out.hex
            a.bin
            b.bin
