name: CI
on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [manual-ci]

jobs:
  say-ok:
    runs-on: ubuntu-latest
    steps:
      - run: echo "OK :: CI triggered (push/workflow_dispatch/repository_dispatch)"
