name: CI
on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      R4_PATH: ${{ github.workspace }}/tools/re4_stream_dummy
      R4_SEED: "1"
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev

      - name: Prepare dummy re4_stream (deterministic zeros)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p tools
          printf '#!/usr/bin/env bash\nexec cat /dev/zero\n' > tools/re4_stream_dummy
          chmod +x tools/re4_stream_dummy
          echo "$PWD/tools" >> "$GITHUB_PATH"

      - name: Build CLI
        shell: bash
        run: |
          set -euo pipefail
          make -B r4cs_cat

      - name: Build demo (local link)
        shell: bash
        run: |
          set -euo pipefail
          gcc -O2 -std=c11 demo.c r4cs.c -lcrypto -lpthread -o demo

      - name: Smoke: 64 bytes hex format
        shell: bash
        env:
          R4_PATH: ${{ github.workspace }}/tools/re4_stream_dummy}
        run: |
          set -euo pipefail
          ./r4cs_cat -n 64 -hex | tee out.hex
          grep -E '^[0-9a-f]{128}$' out.hex

      - name: Smoke: determinism with R4_SEED
        shell: bash
        env:
          R4_PATH: ${{ github.workspace }}/tools/re4_stream_dummy}
          R4_SEED: "1"
        run: |
          set -euo pipefail
          ./r4cs_cat -n 4096 > a.bin
          ./r4cs_cat -n 4096 > b.bin
          cmp -s a.bin b.bin
