name: CI

on:
  push:
    branches: [ main, ci-fix ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev

      - name: Build CLI
        run: |
          mkdir -p bin
          gcc -O2 -std=c11 r4cs_cat.c r4cs.c -I. -lcrypto -lpthread -o bin/r4cs_cat

      - name: Build demo
        run: |
          gcc -O2 -std=c11 demo.c r4cs.c -I. -lcrypto -lpthread -o demo

      - name: Smoke test
        env:
          R4_SEED: "1"
        run: |
          ./demo
          ./bin/r4cs_cat -n 64 -hex
