name: CI

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev

      - name: Build CLI
        run: |
          make -B r4cs_cat

      - name: Build demo (local link)
        run: |
          gcc -O2 -std=c11 demo.c r4cs.c -lcrypto -lpthread -o demo

      - name: Quick run demo
        run: ./demo
